macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

env:
  MACOSX_DEPLOYMENT_TARGET: "10.15"
  LLVM_VER: 16.0.4

task:
  checkout_script:
    - git submodule init
    - git submodule update

  install_deps_script:
    - brew update
    - brew install gcc@11 gnu-tar
    - pip3 install wheel

  download_llvm_script: |
    wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VER/llvm-project-$LLVM_VER.src.tar.xz
    tar xf llvm-project-$LLVM_VER.src.tar.xz
    mv llvm-project-$LLVM_VER.src llvm-project-$LLVM_VER

  build_llvm_libclang_script: |
    mkdir -p llvm-project-$LLVM_VER/build
    cd llvm-project-$LLVM_VER/build
        cmake ../llvm \
          -DLLVM_ENABLE_PROJECTS=clang \
          -DBUILD_SHARED_LIBS=OFF \
          -DLLVM_ENABLE_ZLIB=OFF \
          -DLLVM_ENABLE_ZSTD=OFF \
          -DLLVM_ENABLE_TERMINFO=OFF \
          -DLLVM_TARGETS_TO_BUILD=X86 \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-O2 -g -DNDEBUG -static-libgcc -static-libstdc++" \
          -DCMAKE_C_COMPILER=$(brew --prefix gcc@11)/bin/gcc-11 \
          -DCMAKE_CXX_COMPILER=$(brew --prefix gcc@11)/bin/g++-11 \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
    make libclang -j$(sysctl -n hw.ncpu)

  print_dependencies_script: |
    du -csh llvm-project-$LLVM_VER/build/lib/libclang.dylib
    file llvm-project-$LLVM_VER/build/lib/libclang.dylib
    otool -L llvm-project-$LLVM_VER/build/lib/libclang.dylib

  sha512sum_script: |
    cd llvm-project-$LLVM_VER/build/lib
    shasum -a512 libclang.dylib > libclang.dylib.$LLVM_VER.macosx-amd64.sha512sum
    echo "Checksum is: "
    cat libclang.dylib.$LLVM_VER.macosx-amd64.sha512sum
    gtar zcvf libclang.dylib.$LLVM_VER.macosx-amd64.tar.gz libclang.dylib libclang.dylib.$LLVM_VER.macosx-amd64.sha512sum
    shasum -a512 libclang.dylib.$LLVM_VER.macosx-amd64.tar.gz

  libclang_artifacts:
    path: llvm-project-$LLVM_VER/build/lib/libclang.dylib.$LLVM_VER.macosx-amd64.tar.gz

  generate_wheel_package_script: |
    cp llvm-project-$LLVM_VER/build/lib/libclang.dylib native/
    python3 setup_ext.py bdist_wheel --universal --plat-name=macosx_11_0_arm64

  wheel_artifacts:
    path: dist/*.whl
